### PR TITLE
go back to array-of-structs

### PR DESCRIPTION
**Pull request by jrevels**
This PR is competing with #9. I much prefer this approach if it's workable/if aggressive inlining removes the problems we use to have with it.

### CODE REVIEW

**Comment by vchuravy** [comment]
I will take a look, but I suspect that the memory access patterns will be suboptimal for the GPU, but we can try SoA.jl to do the transformation automatically.

**Comment by maleadt** [comment]
Rebased. Doesn't pass tests though:

```
testing lstm-like kernel for kind `cpu` and fusion_level `1`
LSTM-like kernels: Error During Test at /home/tbesard/Julia/test/runtests.jl:18
  Got an exception of type MethodError outside of a @test
  MethodError: no method matching deriv(::Array{Float32,2})
  Closest candidates are:
    deriv(!Matched::Variable) at src/variables.jl:29
    deriv(!Matched::Record) at src/variables.jl:30
  Stacktrace:
   [1] backward!(::Instruction{typeof(broadcast),Tuple{getfield(, Symbol("##4#6")),Variable{Array{Float32,2}},Variable{Array{Float32,2}},Variable{Array{Float32,2}},Variable{Array{Float32,2}},Variable{Array{Float32,2}}}}) at src/primitives.jl:176
   [2] backward!(::Tape) at src/tape.jl:36
   [3] autograd(::Function, ::Array{Float32,2}, ::Vararg{Array{Float32,2},N} where N) at src/jl:37
   [4] macro expansion at /home/tbesard/Julia/test/runtests.jl:30 [inlined]
   [5] macro expansion at /home/tbesard/Julia/julia-dev/build/release/usr/share/julia/site/v0.7/Test/src/Test.jl:1008 [inlined]
   [6] top-level scope at /home/tbesard/Julia/test/runtests.jl:19
   [7] include at ./boot.jl:292 [inlined]
   [8] include_relative(::Module, ::String) at ./loading.jl:1012
   [9] include(::Module, ::String) at ./sysimg.jl:26
   [10] exec_options(::Base.JLOptions) at ./client.jl:332
   [11] _start() at ./client.jl:447

```

**Comment by jrevels** [comment]
EDIT: comment removed since it's now irrelevant

**Comment by jrevels** [comment]
Okay, tests pass now

**Comment by jrevels** [comment]
This still passes tests after a rebase, so I'll merge now.

**Pull request merged**
