### PR TITLE
GPU-aware automatic SoA transformation

### PR DESCRIPTION
**Pull request by vchuravy**
Ok I have this mostly working.

Status:
- [x] Code duplication between `soa.jl` and `gpu.jl`. The idea is that everthing that works on a `CuArray` should also work on a `StructOfArray{T,N,<:CuArray}`
- [x] Running `benchmarks_no_ad.jl` leads to a `MemoryError` (and `cuda-memcheck`) is no help
- [x] `benchmark_ad.jl` 
  - `fusion=0` works!
  - [x] `fusion=1` does not work
  - [x] `fusion=1` does not work
- [x] Optimise. I haven't optimise or profiled this. Currently the performance doesn't look good.

| environment |   size    | fusion_level |  soa  | forwards  | backwards |
| -----------:|:---------:|:------------:|:-----:|:---------:|:---------:|
|         cpu |  512x512  |      0       | true  | 25.85 ms  | 31.97 ms  |
|  cudanative |  512x512  |      0       | true  | 518.45 us | 620.03 us |
|         cpu |  512x512  |      0       | false | 19.93 ms  | 21.45 ms  |
|  cudanative |  512x512  |      0       | false | 449.75 us | 480.54 us |
|         cpu | 1024x1024 |      0       | true  | 107.24 ms | 126.41 ms |
|  cudanative | 1024x1024 |      0       | true  |  5.93 ms  | 658.89 us |
|         cpu | 1024x1024 |      0       | false | 83.60 ms  | 86.73 ms  |
|  cudanative | 1024x1024 |      0       | false |  5.91 ms  | 541.95 us |
|         cpu | 2048x2048 |      0       | true  | 527.60 ms | 505.25 ms |
|  cudanative | 2048x2048 |      0       | true  |  6.37 ms  |  1.60 ms  |
|         cpu | 2048x2048 |      0       | false | 446.57 ms | 362.15 ms |
|  cudanative | 2048x2048 |      0       | false |  6.33 ms  |  1.59 ms  |

### memory error
```
ERROR: LoadError: CUDA error: an illegal memory access was encountered (code #700, ERROR_ILLEGAL_ADDRESS)
Stacktrace:
 [1] macro expansion at /home/vchuravy/.julia/v0.7/CUDAdrv/src/base.jl:148 [inlined]
 [2] synchronize at /home/vchuravy/.julia/v0.7/CUDAdrv/src/context.jl:191 [inlined] (repeats 2 times)
 [3] cudanative_unfused_lstm_update_c(::StructOfArrays{Float32,2,CuArray{Float32,2},Tuple{CuArray{Float32,2}}}, ::StructOfArrays{Float32,2,CuArray{Float32,2},Tuple
{CuArray{Float32,2}}}, ::StructOfArrays{Float32,2,CuArray{Float32,2},Tuple{CuArray{Float32,2}}}, ::StructOfArrays{Float32,2,CuArray{Float32,2},Tuple{CuArray{Float3
2,2}}}, ::StructOfArrays{Float32,2,CuArray{Float32,2},Tuple{CuArray{Float32,2}}}, ::StructOfArrays{Float32,2,CuArray{Float32,2},Tuple{CuArray{Float32,2}}}, ::Struc
tOfArrays{Float32,2,CuArray{Float32,2},Tuple{CuArray{Float32,2}}}, ::StructOfArrays{Float32,2,CuArray{Float32,2},Tuple{CuArray{Float32,2}}}, ::StructOfArrays{Float
32,2,CuArray{Float32,2},Tuple{CuArray{Float32,2}}}, ::StructOfArrays{Float32,2,CuArray{Float32,2},Tuple{CuArray{Float32,2}}}) at /home/vchuravy/.julia/v0.7/MixedMo
deBroadcastAD/test/perf/../kernels.jl:102
....
========= Internal error (7)
========= No CUDA-MEMCHECK results found
```

### `fusion=1`
```
INFO: benchmarking fusion_level=1 size=512, soa=true
ERROR: LoadError: MethodError: no method matching Float32(::ForwardDiff.Dual{Nothing,Float32,6})                                                                   
Closest candidates are:                                                                                                                                            
  Float32(::Real, !Matched::RoundingMode) where T<:AbstractFloat at rounding.jl:202                                                                                
  Float32(::T<:Number) where T<:Number at boot.jl:683                                                                                                              
  Float32(!Matched::Int8) at float.jl:57                                                                                                                           
  ...                                                                                                                                                              
Stacktrace:                                                                                                                                                        
 [1] Float32(::ForwardDiff.Dual{Nothing,Float32,6}) at ./deprecated.jl:489                                                                                         
 [2] convert at ./number.jl:7 [inlined]                                                                                                                            
 [3] setindex! at ./array.jl:690 [inlined]                                                                                                                         
 [4] copyto!(::IndexLinear, ::Array{Float32,2}, ::IndexLinear, ::Array{ForwardDiff.Dual{Nothing,Float32,6},2}) at ./abstractarray.jl:695                           
 [5] copyto! at ./abstractarray.jl:687 [inlined]                                                                                                                   
 [6] Type at ./array.jl:416 [inlined]                                                                                                                              
 [7] convert at ./abstractarray.jl:15 [inlined]                                                                                                                    
 [8] convert at ./essentials.jl:226 [inlined]                                                                                                                      
 [9] StructOfArrays{ForwardDiff.Dual{Nothing,Float32,6},2,Array{ForwardDiff.Dual{Nothing,Float32,6},2},Tuple{Array{Float32,2},Array{ForwardDiff.Partials{6,Float32}
,2}}}(::Tuple{Array{ForwardDiff.Dual{Nothing,Float32,6},2},Array{ForwardDiff.Dual{Nothing,Float32,6},2}}) at /home/vchuravy/.julia/v0.7/MixedModeBroadcastAD/src/so
a.jl:6                                                                                                                                                             
 [10] @generated body at /home/vchuravy/.julia/v0.7/MixedModeBroadcastAD/src/soa.jl:16 [inlined]                                                                   
 [11] Type at /home/vchuravy/.julia/v0.7/MixedModeBroadcastAD/src/soa.jl:16 [inlined]                                                                              
 [12] Type at /home/vchuravy/.julia/v0.7/MixedModeBroadcastAD/src/soa.jl:28 [inlined]                                                                              
 [13] broadcast_similar at /home/vchuravy/.julia/v0.7/MixedModeBroadcastAD/src/soa.jl:38 [inlined]                                                                 
 [14] broadcast at ./broadcast.jl:633 [inlined]                                                                                                                    
 [15] broadcast at ./broadcast.jl:618 [inlined]                                                                                                                    
 [16] broadcast at ./broadcast.jl:615 [inlined]                                                                                                                    
 [17] @generated body at /home/vchuravy/.julia/v0.7/FastSplat/src/FastSplat.jl:51 [inlined]                                                                        
 [18] ##gen#1434 at /home/vchuravy/.julia/v0.7/FastSplat/src/FastSplat.jl:48 [inlined]                                                                             
 [19] dual_eval_broadcast!(::getfield(, Symbol("##3#5")), ::StructOfArrays{Float32,2,Array{Float32,2},Tuple{Array{Float32,2}}}, ::NTuple{6,StructOfArrays{Float32,2
,Array{Float32,2},Tuple{Array{Float32,2}}}}) at /home/vchuravy/.julia/v0.7/MixedModeBroadcastAD/src/primitives.jl:96                                               
 [20] forward!(::MixedModeBroadcastAD.Instruction{typeof(broadcast),Tuple{getfield(, Symbol("##3#5")),MixedModeBroadcastAD.Variable{StructOfArrays{Float32,2,Array{
Float32,2},Tuple{Array{Float32,2}}}},MixedModeBroadcastAD.Variable{StructOfArrays{Float32,2,Array{Float32,2},Tuple{Array{Float32,2}}}},MixedModeBroadcastAD.Variabl
e{StructOfArrays{Float32,2,Array{Float32,2},Tuple{Array{Float32,2}}}},MixedModeBroadcastAD.Variable{StructOfArrays{Float32,2,Array{Float32,2},Tuple{Array{Float32,2
}}}},MixedModeBroadcastAD.Variable{StructOfArrays{Float32,2,Array{Float32,2},Tuple{Array{Float32,2}}}},MixedModeBroadcastAD.Variable{StructOfArrays{Float32,2,Array
{Float32,2},Tuple{Array{Float32,2}}}}}}) at /home/vchuravy/.julia/v0.7/MixedModeBroadcastAD/src/primitives.jl:83                                                   
 [21] forward!(::MixedModeBroadcastAD.Tape) at /home/vchuravy/.julia/v0.7/MixedModeBroadcastAD/src/tape.jl:29
```

### CODE REVIEW

**Comment by maleadt** [comment]
Do you still have unpushed local changes? `profile_ad.jl` doesn't work.

**Comment by vchuravy** [comment]
No no local changes.


| environment |   size    | fusion_level |  soa  |  elapsed  |      
| -----------:|:---------:|:------------:|:-----:|:---------:|      
|         cpu |  512x512  |      0       | true  | 25.02 ms  |      
|  cudanative |  512x512  |      0       | true  |  3.41 ms  |      
|         cpu |  512x512  |      0       | false | 19.89 ms  |      
|  cudanative |  512x512  |      0       | false |  3.31 ms  |      
|     cudaraw |  512x512  |      0       | false |  2.70 ms  |     
|         cpu | 1024x1024 |      0       | true  | 104.05 ms |      
|  cudanative | 1024x1024 |      0       | true  |  5.87 ms  |      
|         cpu | 1024x1024 |      0       | false | 83.21 ms  |      
|  cudanative | 1024x1024 |      0       | false |  5.79 ms  |      
|     cudaraw | 1024x1024 |      0       | false |  5.47 ms  |      
|         cpu | 2048x2048 |      0       | true  | 443.59 ms |      
|  cudanative | 2048x2048 |      0       | true  |  6.21 ms  |      
|         cpu | 2048x2048 |      0       | false | 335.61 ms |      
|  cudanative | 2048x2048 |      0       | false |  6.08 ms  |      
|     cudaraw | 2048x2048 |      0       | false |  6.21 ms  |      
|         cpu |  512x512  |      1       | true  | 30.08 ms  |      
|  cudanative |  512x512  |      1       | true  | 971.41 us |      
|         cpu |  512x512  |      1       | false | 22.55 ms  |      
|  cudanative |  512x512  |      1       | false | 916.61 us |      
|         cpu | 1024x1024 |      1       | true  | 121.02 ms |      
|  cudanative | 1024x1024 |      1       | true  |  1.40 ms  |      
|         cpu | 1024x1024 |      1       | false | 92.27 ms  |      
|  cudanative | 1024x1024 |      1       | false |  1.38 ms  |      
|         cpu | 2048x2048 |      1       | true  | 492.78 ms |      
|  cudanative | 2048x2048 |      1       | true  |  1.55 ms  |      
|         cpu | 2048x2048 |      1       | false | 369.74 ms |      
|  cudanative | 2048x2048 |      1       | false |  1.50 ms  |      
|         cpu |  512x512  |      2       | true  | 33.83 ms  |      
|  cudanative |  512x512  |      2       | true  | 182.34 us |      
|         cpu |  512x512  |      2       | false | 24.84 ms  |      
|  cudanative |  512x512  |      2       | false | 140.35 us |      
|     cudaraw |  512x512  |      2       | false | 88.30 us  |      
|         cpu | 1024x1024 |      2       | true  | 135.09 ms |      
|  cudanative | 1024x1024 |      2       | true  | 960.30 us |      
|         cpu | 1024x1024 |      2       | false | 99.50 ms  |      
|  cudanative | 1024x1024 |      2       | false | 952.05 us |      
|     cudaraw | 1024x1024 |      2       | false | 856.92 us |      
|         cpu | 2048x2048 |      2       | true  | 539.85 ms |      
|  cudanative | 2048x2048 |      2       | true  |  1.18 ms  |      
|         cpu | 2048x2048 |      2       | false | 398.40 ms |      
|  cudanative | 2048x2048 |      2       | false |  1.14 ms  |      
|     cudaraw | 2048x2048 |      2       | false |  1.09 ms  |

**Comment by vchuravy** [comment]
So for the `benchmark_no_ad.jl` looks like I would expect it, except for the CPU case.
Adding or removing SoA should not matter at all in this case since we are only working with scalars.

**Comment by vchuravy** [comment]
Ok this now works. Still have optimisation left and we will need to implement recursive SoA which shouldn't be that hard since Keno has done it for SoA.jl

**Comment by jrevels** [comment]
I noticed something fairly important while looking at Valentin's profile of this branch. The forward pass compute time is quite low - most of the time is spent in allocations that are cacheable, so when we turn on caching, our performance will be quite good.

This is actually more significant than it may seem at first brush. It indicates another benefit to the mixed-mode approach - if you use our method, we can cache your allocations without needing to eagerly evaluate all branches, which is what would be necessary to fully pre-allocate memory in the coarse-grained dynamic regime. I reckon that many dynamic implementations don't even bother automatically caching allocations in such subgraphs for this reason - at least, they probably force it to be a manual per-variable decision if they can't infer some special structure on the subgraph. Placing the control flow in the scalar kernel essentially gives us this inference for free, and using forward-mode means our memory caching pattern should be far simpler.

**Comment by vchuravy** [comment]
As Jarrett noted the performance of the compute part of the kernels improved, but this is now causing multiple allocations instead of one large one which apparently is a lot slower.
Tests  are now passing.

**Pull request merged**
