### PR TITLE
rewrite for lstm benchmark kernel

### PR DESCRIPTION
**Pull request by jrevels**
Adds a kernel which executes the part of an LSTM layer that stresses fuseable broadcast operations. I used the formula in the [cuDNN paper](https://arxiv.org/pdf/1604.01946.pdf) as a reference for the kernel. 

This also rewrites the ad hoc AD framework to separate out the record and forward passes.

I haven't actually run this code yet, of course 😛 

I haven't yet implemented a way to run the benchmark in "unfused" mode. It's technically easy to implement, but the code to do so would be pretty ugly without https://github.com/JuliaLang/julia/pull/25377. Shall we wait for that to be merged?

If anybody can help point me to what I should do for `cuda_lstm_update`, I'd be grateful for the help.

TODO:

- [ ] implement `cuda_lstm_update`
- [ ] implement unfused version
- [ ] actually run the code/get tests passing

### CODE REVIEW

**Comment by maleadt** [comment]
> If anybody can help point me to what I should do for cuda_lstm_update, I'd be grateful for the help.

The only GPU kernels come from the GEMMs and the broadcast, so just broadcast the correct functions (`CUDAnative.tanh`, `CUDAnative.exp`, and derivatives) and you should be all set.

**Comment by maleadt** [comment]
I think we should be able to get pretty close to the [fused reference kernel](https://github.com/parallel-forall/code-samples/blob/master/posts/rnn/LSTM.cu#L213-L254), except that we'll be spawning two dependent kernels, one for [each broadcast](https://github.com/jrevels/MixedModeBroadcastAD.jl/blob/ac15fe4fbda5eb387fdf45bf235ad0431e848b0d/src/kernels.jl#L16-L17). Or does lazy broadcasting allow to merge these?
Would need https://github.com/JuliaLang/julia/issues/22129 to do this manually.

Depending on how this turns out, time left, scope, ... we could also try and include the combined GEMMs (optimization 1) and automatically schedule them on independent streams (optimization 2). This would be pretty naive (lacking a dependence graph), but would work for this simple model.

**Comment by jrevels** [comment]
> I think we should be able to get pretty close to the fused reference kernel, except that we'll be spawning two dependent kernels, one for each broadcast. Or does lazy broadcasting allow to merge these?

After thinking about it, we don't need to do both `c` and `h` updates to meaningfully benchmark our paper's technique, so I've just removed the `h` update code. 

We only need to show that our technique works on a single fused broadcast kernel - how that fusion actually happens on the front-end is mostly irrelevant to our paper's technique.

> Depending on how this turns out, time left, scope, ... we could also try and include the combined GEMMs (optimization 1) and automatically schedule them on independent streams (optimization 2). This would be pretty naive (lacking a dependence graph), but would work for this simple model.

Feel free to play around with it if you want, of course, but the performance of the GEMMs is irrelevant to the paper. Our paper isn't about LSTM performance, but about differentiating through "opaquely fused" broadcast kernels without needing to allocate/compile additional tapes/CGs for the kernel. Fused broadcast operations pop up naturally in part of an LSTM kernel, and LSTMs are familiar territory for ML folks, so we're using that small part of the LSTM kernel as an example to demonstrate that the fused AD works. However, we could've chosen some other, non-LSTM example and equally applied our technique there.

**Comment by maleadt** [comment]
This doesn't work? There's a trivial import typo, but even then the LSTM example doesn't work.

**Comment by jrevels** [comment]
Ah, I had an itchy trigger finger. I'll push a fix soon.

**Pull request merged**
