### PR TITLE
WIP: Manually fuse the backwards pass.

### PR DESCRIPTION
**Pull request by maleadt**
Passes tests, but initial performance is disappointing. Not optimized/profiled yet, just putting this out here.

```
| environment | precomputed layers? | SoA enabled? | size | forward time | backward time |
| -----------:|:-------------------:|:------------:|:----:|:------------:|:-------------:|
|        :gpu |        false        |     true     | 512  |  221.94 us   |   275.81 us   |
|        :gpu |        false        |     true     | 1024 |  310.79 us   |   393.63 us   |
|        :gpu |        false        |     true     | 2048 |  706.35 us   |   854.80 us   |
|        :gpu |        true         |     true     | 512  |  158.44 us   |   218.84 us   |
|        :gpu |        true         |     true     | 1024 |  185.68 us   |   270.01 us   |
|        :gpu |        true         |     true     | 2048 |  398.71 us   |   462.64 us   |
```

Reference: `jr/backunroll`

```
| environment | precomputed layers? | SoA enabled? | size | forward time | backward time |
| -----------:|:-------------------:|:------------:|:----:|:------------:|:-------------:|
|        :gpu |        false        |     true     | 512  |  217.51 us   |   387.10 us   |
|        :gpu |        false        |     true     | 1024 |  313.08 us   |   400.87 us   |
|        :gpu |        false        |     true     | 2048 |  706.70 us   |    1.00 ms    |
|        :gpu |        true         |     true     | 512  |  160.53 us   |   225.82 us   |
|        :gpu |        true         |     true     | 1024 |  195.48 us   |   243.57 us   |
|        :gpu |        true         |     true     | 2048 |  405.19 us   |   460.17 us   |
```

### CODE REVIEW

**Comment by maleadt** [comment]
Updated timings with unrolling taken into account. It is as fast now. Yay..

**Comment by maleadt** [comment]
# Memop measurements

Kernels:

- 1 arg: `tanh(x)`
- 2 arg: `tanh(x+y)`
- 10/12 args: `hmlstm`, with 2 non differentiable bools


## unfused

- 1 arg
  - size 1
    - forwards: 1 load, 2 stores
    - backwards: 3 loads, 1 store
  - size 2048×2048
    - forwards: 131.072 loads, 524.288 stores
    - backwards: 524.288 loads, 131.072 stores

- 2 args
  - size 1
    - forwards: 2 loads, 3 stores
    - backwards: 2×3 loads, 2×1 stores
  - size 2048×2048
    - forwards: 262.144 loads, 1.179.648 stores
    - backwards: 2×655.360 loads, 2×131.072 stores
10% overhead

- 10/12 args
  - size 1
    - forwards: 7-9 loads, 13 stores
    - backwards: 10×3 loads, 10×1 stores
  - size 2048×2048
    - forwards: 1.572.864 loads, 22.151.168 stores
    - backwards: 10×1.966.080 loads, 10×131.072 stores


## unfused+soa

size 1: as non-SOA

- 1 arg
  - size 2048×2048
    - forwards: 131.072 loads, 262.144 stores
    - backwards: 393.216 loads, 131.072 stores

- 2 args
  - size 2048×2048
    - forwards: 262.144 loads, 393.216 stores
    - backwards: 2×393.216 loads, 2×131.072 stores

- 10/12 args
  - size 2048×2048
    - forwards: 1.572.864 loads, 1.703.936 stores
    - backwards: 10×393.216 loads, 10×131.072 stores

conclusion: SOA reduces

- forward stores
- backward loads (nicely keeping the loads identical, regardless of arity)


## fused

forwards: as unfused

1 arg: identical to unfused

- 2 args
  - size 1
    - backwards: 5 loads, 2 stores
  - size 2048×2048
    - backwards: 1.179.648 loads, 262.144 stores

- 10/12 args
  - size 1
    - backwards: 21 loads, 10 stores
  - size 2048×2048
    - backwards: 18.481.152 loads, 1.310.720 stores

conclusion: fusion reduces backward loads with about 5-10%


## fused+soa

forwards: as unfused+soa

size 1: as non-SOA

- 1 arg
  - size 2048×2048
    - backwards: 393.216 loads: 131.072 stores

- 2 args
  - size 2048×2048
    - backwards: 655.360 loads, 262.144 stores

- 10/12 args
  - size 2048×2048
    - backwards: 2.752.512 loads, 1.310.720 stores

conclusion: further reduces backward loads, but not enough to reach forwards pass

**Comment by maleadt** [comment]
I think I found out why the forwards pass is better suited for SOA. I did some low-level analysis, with a 1-arg Float32 kernel (ie. `sizeof(T)==4`, `sizeof(Dual)==8`) printing base pointers and element size for all array operations. The forwards pass yields, without SOA:

```
load 4 from 0xb05500a00
store 8 to  0xb05500e00
```

This means that we're storing to an array of Dual's. How does the IR look?

```
%77 = inttoptr i64 %74 to { float, { [1 x float] } }*
%78 = getelementptr inbounds { float, { [1 x float] } }, { float, { [1 x float] } }* %77, i64 %15, i32 0
%79 = addrspacecast float* %78 to float addrspace(1)*
store float %s.2.i, float addrspace(1)* %79, align 4
%80 = getelementptr inbounds { float, { [1 x float] } }, { float, { [1 x float] } }* %77, i64 %15, i32 1, i32 0, i64 0
%81 = addrspacecast float* %80 to float addrspace(1)*
store float %76, float addrspace(1)* %81, align 4
```

So we're storing each component of the dual individually (LLVM apparently can't/doesn't merge these stores), implying a non-contiguous memory pattern that can't get merged.

Switching to SOA, we see:

```
load 4 from 0xb05500a00
store 4 to  0xb05500e00
store 4 to  0xb05501000
```

So SOA has split this array of duals into two arrays, and as a result storing the Dual components separately now does so in a coalescable manner (accesses across threads target contiguous memory).


Doing the same analysis for the backwards pass, without SOA:

```
load 4 from 0xb05500600
load 4 from 0xb05500c00
load 8 from 0xb05500e00
store 4 to  0xb05500600
```

So there's only one load out of 4 memops that targets non-contiguous elements. And indeed, enabling SOA:

```
load 4 from 0xb05500600
load 4 from 0xb05500c00
load 4 from 0xb05500e00
load 4 from 0xb05501000
store 4 to  0xb05500600
```


Kind of a backwards way of analyzing this, but does seem to prove the point that the forwards kernel is better suited for SOA.


(on a tangential note, I would have expected LLVM to merge the memory operations on individual dual components. we probably would need to attach proper TBAA info. but it wouldn't improve the higher-arity case, so it's better to rely on SoA to optimize layout and let the GPU merge operations)

**Comment by maleadt** [comment]
Comment from @jrevels: both the forwards pass and backwards pass should be doing essentially the same memory ops

for arity = `n`, and normalized to `T` size, I’d expect the ops count to vaguely look like the following for each elementwise application (excuse the shitty notation):

```#== forwards pass ==#

co_load  n       # input values
co_store (n + 1) # output duals
load     1       # value(output duals)
store    1       # value(output duals) -> output value

#== backwards pass ==#

load     1  # output derivative
co_load  n  # output dual
co_load  n  # input derivatives
co_store n  # input derivatives
```

where some of the load/store pairs there are essentially inplace updates so I’m not sure whether they are further optimized on the instruction level

**Comment by jrevels** [comment]
> Comment from @jrevels: both the forwards pass and backwards pass should be doing essentially the same memory ops
> for arity = n, and normalized to T size, I’d expect the ops count to vaguely look like the following for each elementwise application (excuse the shitty notation):
> ...

Theoretically, with #22, the backwards pass should no longer need to do some of those add/loads:

```
#== backwards pass ==#

load     1  # output derivative
co_load  n  # output dual
co_store n  # input derivatives
```

**Pull request closed without merging**
