### PR TITLE
add naive downstream counter to variables, enabling load/add elision for certain backwards pass operations

### PR DESCRIPTION
**Pull request by jrevels**
This should get rid of an extra set of load/adds in the backwards pass without sacrificing correctness.

### CODE REVIEW

**Comment by maleadt** [comment]
OK, some results. Only going to measure _kernel times_, which is relevant here. We can optimize CPU times afterwards (#20).

For reference, on current master, 100 iterations on 2048x2048, SOA without precompute:

```
==10782== NVTX result:
==10782==   Thread "<unnamed>" (id = 2989644992)
==10782==     Domain "<unnamed>"
==10782==       Range "backward pass"
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:   10.05%  8.5405ms       100  85.405us  84.799us  86.015us  ptxcall__broadcast__9
                   10.02%  8.5173ms       100  85.173us  84.447us  85.759us  ptxcall__broadcast__6
                   10.01%  8.5093ms       100  85.092us  84.255us  86.239us  ptxcall__broadcast__7
                   10.01%  8.5050ms       100  85.050us  84.287us  86.175us  ptxcall__broadcast__5
                    9.99%  8.4941ms       100  84.941us  84.351us  85.695us  ptxcall__broadcast__12
                    9.99%  8.4907ms       100  84.907us  84.127us  85.855us  ptxcall__broadcast__10
                    9.99%  8.4879ms       100  84.878us  84.159us  85.759us  ptxcall__broadcast__11
                    9.99%  8.4863ms       100  84.863us  84.287us  85.823us  ptxcall__broadcast__13
                    9.98%  8.4817ms       100  84.817us  84.063us  85.791us  ptxcall__broadcast__8
                    9.97%  8.4753ms       100  84.752us  84.223us  86.047us  ptxcall__broadcast__14

==10782==       Range "forward pass"
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:   91.37%  49.893ms       100  498.93us  495.29us  504.19us  ptxcall__broadcast__3
                    8.63%  4.7109ms       100  47.108us  45.727us  48.416us  ptxcall__broadcast__4
```

forwards 540us vs backwards 840us

Fusing the backwards kernel (#21):

```
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:  100.00%  62.669ms       100  626.69us  625.40us  628.28us  ptxcall__backprop_partial_broadcast__5
```

Quite an improvement, but not enough.

Adding dependency analysis from #22 to the mix (https://github.com/jrevels/MixedModeBroadcastAD.jl/tree/tb/fuse_backwards_multivariable):

```
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:  100.00%  42.845ms       100  428.45us  427.48us  429.21us  ptxcall__backprop_partial_broadcast__5
```

So now we finally beat the forwards pass.

**Comment by maleadt** [comment]
Total compute time (CPU+GPU) is probably going to be worse though, because it doesn't contain the unrolling from #20 (accessing `.downstreams` isn't possible from a generated function).

**Comment by jrevels** [comment]
> Total compute time (CPU+GPU) is probably going to be worse though, because it doesn't contain the unrolling from #20 (accessing .downstreams isn't possible from a generated function).

Can we just do the check at runtime/would that help? The same branch should always be taken for our benchmark, so maybe the non-taken branch will just get thrown away by the GPU anyway?

**Comment by maleadt** [comment]
> Can we just do the check at runtime/would that help?

Yes, but to have `downstreams` available on the GPU means looping through the args and checking for `<: Variable`, so not much to gain? Or am I misunderstanding something?

EDIT: but that check can happen `@generated`, ok I see.

**Pull request merged**
