### PR TITLE
add ability to mark differentiable parameters to broadcast_gradients! (fix #36)

### LINKED ISSUE #36: Don't differentiate boundary states in Julia code
I'm having trouble justifying our differentiation of the boundary states (the `z`s) in the paper...there's really no good reason for it other than that "well we never got around to *not* differentiating them."

Our options for resolving this are either:

1. Implement variable selection in our prototype
2. Just close over the `z`s before broadcasting the kernel

I can implement option 1 myself if need be, but option 2 would be much nicer/more natural if CUDAnative can handle it. I recall being told that option 2 has performance problems since CUDAnative doesn't like it when a kernel loads from a closed-over buffer. Thoughts @maleadt / @vchuravy?

### PR DESCRIPTION
**Pull request by jrevels**
It turns out that we had to generate the closure mentioned in #36 at the scalar level anyway, since that's where the AD is happening...so I basically just went all the way and implemented arbitrary marking for differentiable parameters.

Apologies to @maleadt - my original plan was to do a much simpler closure over the arrays that would've required https://github.com/JuliaGPU/CUDAnative.jl/pull/176, but my idea didn't end up being correct :/ sorry for wasting your time. At least, it's cool that CUDAnative supports closures now!

I still need to run this branch's tests on Cyclops.

### CODE REVIEW

**Comment by jrevels** [comment]
Okay, after fixing some silly typos and indexing problems, this passes tests. Now to run the benchmarks...

**Comment by jrevels** [comment]
executing `runbenchmarks.jl` with this branch:

```
| TF-style? | on GPU? | size |   time    |
| ---------:|:-------:|:----:|:---------:|
|     false |  false  | 512  | 34.22 ms  |
|     false |  false  | 1024 | 134.50 ms |
|     false |  false  | 2048 | 543.94 ms |
|     false |  true   | 512  | 87.27 us  |
|     false |  true   | 1024 | 124.04 us |
|     false |  true   | 2048 | 275.02 us |
|      true |  false  | 512  | 28.96 ms  |
|      true |  false  | 1024 | 116.58 ms |
|      true |  false  | 2048 | 473.38 ms |
|      true |  true   | 512  | 187.33 us |
|      true |  true   | 1024 | 209.64 us |
|      true |  true   | 2048 | 514.90 us |
```

Hmm. Doesn't seem to have improved much/at all? But the TF-style timings also seem to have decreased from the last run I'm comparing with, and this PR shouldn't affect that, so maybe I'm not doing this right...@maleadt any tips? This PR definitely reduces the theoretically required amount of compute/memory usage for each `dual_kernel` invocation (fewer derivatives propagating through the computation), so I was hoping for a bigger improvement.

I'll do another run against master, just in case environmental changes on Cyclops are to blame...

**Comment by jrevels** [comment]
Here are the results for the run I just did on master:

```
| TF-style? | on GPU? | size |   time    |
| ---------:|:-------:|:----:|:---------:|
|     false |  false  | 512  | 40.60 ms  |
|     false |  false  | 1024 | 165.91 ms |
|     false |  false  | 2048 | 664.30 ms |
|     false |  true   | 512  | 81.21 us  |
|     false |  true   | 1024 | 126.21 us |
|     false |  true   | 2048 | 288.53 us |
|      true |  false  | 512  | 29.54 ms  |
|      true |  false  | 1024 | 120.43 ms |
|      true |  false  | 2048 | 492.08 ms |
|      true |  true   | 512  | 180.80 us |
|      true |  true   | 1024 | 207.04 us |
|      true |  true   | 2048 | 512.19 us |
```

Looks like this isn't causing a huge difference.

Just to comment further on the theoretical implications of decreasing arity: 

Using our forward-mode technique, computing the gradient for a given kernel invocation requires `n^2` perturbation coefficients propagating through the function, and `n` additional multiplications per operation per differentiable input where `n` is the number of inputs being differentiated. Before this PR, `n=6` for our HMLSTM benchmark. With this PR, `n=4` for our HMLSTM benchmark. So, with this PR, we should be paying roughly ~40% of the cost for perturbation memory and ~60% of the cost for the additional multiplies per operation per input that we're paying on master. 

Of course, the runtime includes the cost of other things as well (e.g. warp divergence penalty, 2x primitive execution overhead, etc.), so maybe it's reasonable that changing arity might not have that much overall effect on runtime (as long as we're not in the high-arity "running out of local memory" regime that we want to demonstrate with our arity scaling benchmark). 

@maleadt might be worth poking around the generated code here just to make sure there aren't any additional optimizable implementation costs (e.g. index computation) that could be masking other benefits.

**Comment by maleadt** [comment]
OK, finally some measurements incoming. Didn't have time to do any in depth analysis yet, but it seems like it doesn't make a difference on the arity scaling kernel, but does so with the normal non-TFstyle one.

Arity scaling:

```

julia> df = process("test/reference"); df[.!ismissing.(df[:arity]), :]
12×13 DataFrame
│ Row │ system │ TFstyle │ arity │ dims │ duration        │ kernel_count │ kernel_registers │ kernel_duration   │ kernel_occupancy │ memcpy_count │ memcpy_duration │ api_count │ api_duration    │
├─────┼────────┼─────────┼───────┼──────┼─────────────────┼──────────────┼──────────────────┼───────────────────┼──────────────────┼──────────────┼─────────────────┼───────────┼─────────────────┤
│ 1   │ julia  │ missing │ 1     │ 512  │ 112.204±4.95799 │ 1            │ 22               │ 6.22528±0.0539488 │ 0.602712         │ 0            │ 0.0±0.0         │ 4         │ 57.5718±3.59687 │
│ 2   │ julia  │ missing │ 4     │ 512  │ 132.148±20.6821 │ 1            │ 32               │ 13.5139±0.198848  │ 0.712391         │ 0            │ 0.0±0.0         │ 4         │ 66.4598±8.22244 │
│ 3   │ julia  │ missing │ 7     │ 512  │ 145.303±52.9587 │ 1            │ 48               │ 22.8881±0.259312  │ 0.51977          │ 0            │ 0.0±0.0         │ 4         │ 67.0524±33.2268 │
│ 4   │ julia  │ missing │ 10    │ 512  │ 147.246±15.3944 │ 1            │ 56               │ 31.7068±0.342772  │ 0.434694         │ 0            │ 0.0±0.0         │ 4         │ 65.6052±9.02973 │
│ 5   │ julia  │ missing │ 1     │ 1024 │ 124.171±14.1462 │ 1            │ 22               │ 15.5621±0.15393   │ 0.805425         │ 0            │ 0.0±0.0         │ 4         │ 62.9544±6.95074 │
│ 6   │ julia  │ missing │ 4     │ 1024 │ 150.099±17.2904 │ 1            │ 32               │ 45.6042±0.269547  │ 0.882711         │ 0            │ 0.0±0.0         │ 4         │ 64.626±7.82236  │
│ 7   │ julia  │ missing │ 7     │ 1024 │ 181.588±4.72558 │ 1            │ 48               │ 76.9966±0.389659  │ 0.56605          │ 0            │ 0.0±0.0         │ 4         │ 64.3818±3.94295 │
│ 8   │ julia  │ missing │ 10    │ 1024 │ 227.105±13.9096 │ 1            │ 56               │ 109.162±0.456857  │ 0.456904         │ 0            │ 0.0±0.0         │ 4         │ 68.867±9.48316  │
│ 9   │ julia  │ missing │ 1     │ 2048 │ 151.709±22.6583 │ 1            │ 22               │ 48.942±0.159882   │ 0.861008         │ 0            │ 0.0±0.0         │ 4         │ 63.704±12.3459  │
│ 10  │ julia  │ missing │ 4     │ 2048 │ 272.144±5.54866 │ 1            │ 32               │ 168.133±0.315349  │ 0.921335         │ 0            │ 0.0±0.0         │ 4         │ 62.5887±4.15626 │
│ 11  │ julia  │ missing │ 7     │ 2048 │ 386.548±8.61874 │ 1            │ 48               │ 291.171±0.28442   │ 0.577156         │ 0            │ 0.0±0.0         │ 4         │ 56.1367±6.52044 │
│ 12  │ julia  │ missing │ 10    │ 2048 │ 520.286±9.40031 │ 1            │ 56               │ 416.385±0.583436  │ 0.460154         │ 0            │ 0.0±0.0         │ 4         │ 57.1496±7.62487 │

julia> df = process("test/selectwrt"); df[.!ismissing.(df[:arity]), :]
12×13 DataFrame
│ Row │ system │ TFstyle │ arity │ dims │ duration        │ kernel_count │ kernel_registers │ kernel_duration   │ kernel_occupancy │ memcpy_count │ memcpy_duration │ api_count │ api_duration    │
├─────┼────────┼─────────┼───────┼──────┼─────────────────┼──────────────┼──────────────────┼───────────────────┼──────────────────┼──────────────┼─────────────────┼───────────┼─────────────────┤
│ 1   │ julia  │ missing │ 1     │ 512  │ 98.4201±18.0141 │ 1            │ 22               │ 6.26157±0.0586199 │ 0.600401         │ 0            │ 0.0±0.0         │ 4         │ 46.1539±12.2284 │
│ 2   │ julia  │ missing │ 4     │ 512  │ 136.082±46.2659 │ 1            │ 32               │ 13.5698±0.226387  │ 0.71108          │ 0            │ 0.0±0.0         │ 4         │ 62.8921±27.6326 │
│ 3   │ julia  │ missing │ 7     │ 512  │ 127.58±41.7224  │ 1            │ 48               │ 22.9173±0.289318  │ 0.519329         │ 0            │ 0.0±0.0         │ 4         │ 58.6521±30.3793 │
│ 4   │ julia  │ missing │ 10    │ 512  │ 154.927±38.4111 │ 1            │ 56               │ 31.7864±0.433249  │ 0.434634         │ 0            │ 0.0±0.0         │ 4         │ 68.0763±28.9576 │
│ 5   │ julia  │ missing │ 1     │ 1024 │ 139.737±47.0358 │ 1            │ 22               │ 15.5732±0.165897  │ 0.80526          │ 0            │ 0.0±0.0         │ 4         │ 70.2959±33.9174 │
│ 6   │ julia  │ missing │ 4     │ 1024 │ 156.863±45.1773 │ 1            │ 32               │ 45.5834±0.254923  │ 0.882617         │ 0            │ 0.0±0.0         │ 4         │ 66.6304±35.4445 │
│ 7   │ julia  │ missing │ 7     │ 1024 │ 198.834±37.5193 │ 1            │ 48               │ 76.9986±0.363331  │ 0.565966         │ 0            │ 0.0±0.0         │ 4         │ 70.5024±28.8861 │
│ 8   │ julia  │ missing │ 10    │ 1024 │ 201.374±14.7878 │ 1            │ 56               │ 109.239±0.482714  │ 0.456971         │ 0            │ 0.0±0.0         │ 4         │ 47.9928±12.4665 │
│ 9   │ julia  │ missing │ 1     │ 2048 │ 161.864±43.6051 │ 1            │ 22               │ 48.9725±0.151691  │ 0.860982         │ 0            │ 0.0±0.0         │ 4         │ 67.1838±33.3365 │
│ 10  │ julia  │ missing │ 4     │ 2048 │ 269.238±28.4054 │ 1            │ 32               │ 168.054±0.288969  │ 0.921038         │ 0            │ 0.0±0.0         │ 4         │ 60.2703±27.2206 │
│ 11  │ julia  │ missing │ 7     │ 2048 │ 385.36±19.0496  │ 1            │ 48               │ 291.156±0.356915  │ 0.577165         │ 0            │ 0.0±0.0         │ 4         │ 50.7481±12.6131 │
│ 12  │ julia  │ missing │ 10    │ 2048 │ 540.747±39.8206 │ 1            │ 56               │ 415.463±0.419159  │ 0.460155         │ 0            │ 0.0±0.0         │ 4         │ 74.5502±39.0589 │
```

Regular HMLSTM kernel:

```
julia> df = process("test/reference"); df[.!ismissing.(df[:TFstyle]), :]
6×13 DataFrame
│ Row │ system │ TFstyle │ arity   │ dims │ duration        │ kernel_count │ kernel_registers │ kernel_duration  │ kernel_occupancy │ memcpy_count │ memcpy_duration │ api_count │ api_duration    │
├─────┼────────┼─────────┼─────────┼──────┼─────────────────┼──────────────┼──────────────────┼──────────────────┼──────────────────┼──────────────┼─────────────────┼───────────┼─────────────────┤
│ 1   │ julia  │ true    │ missing │ 512  │ 350.825±116.494 │ 7            │ 164              │ 57.4131±0.315278 │ 0.662044         │ 0            │ 0.0±0.0         │ 16        │ 175.557±81.835  │
│ 2   │ julia  │ false   │ missing │ 512  │ 129.677±5.27804 │ 1            │ 42               │ 20.8932±0.324146 │ 0.506081         │ 0            │ 0.0±0.0         │ 4         │ 64.1985±4.0184  │
│ 3   │ julia  │ true    │ missing │ 1024 │ 382.935±28.2439 │ 7            │ 164              │ 139.507±0.352638 │ 0.823638         │ 0            │ 0.0±0.0         │ 16        │ 193.416±18.2703 │
│ 4   │ julia  │ false   │ missing │ 1024 │ 174.168±22.0092 │ 1            │ 42               │ 63.1111±0.445101 │ 0.552884         │ 0            │ 0.0±0.0         │ 4         │ 66.2754±11.2698 │
│ 5   │ julia  │ true    │ missing │ 2048 │ 593.161±54.5651 │ 7            │ 164              │ 448.066±0.408642 │ 0.869901         │ 0            │ 0.0±0.0         │ 16        │ 196.38±69.2651  │
│ 6   │ julia  │ false   │ missing │ 2048 │ 329.359±5.03762 │ 1            │ 42               │ 223.534±0.398701 │ 0.566508         │ 0            │ 0.0±0.0         │ 4         │ 62.4433±3.82786 │

julia> df = process("test/selectwrt"); df[.!ismissing.(df[:TFstyle]), :]
6×13 DataFrame
│ Row │ system │ TFstyle │ arity   │ dims │ duration        │ kernel_count │ kernel_registers │ kernel_duration  │ kernel_occupancy │ memcpy_count │ memcpy_duration │ api_count │ api_duration    │
├─────┼────────┼─────────┼─────────┼──────┼─────────────────┼──────────────┼──────────────────┼──────────────────┼──────────────────┼──────────────┼─────────────────┼───────────┼─────────────────┤
│ 1   │ julia  │ true    │ missing │ 512  │ 293.306±63.2238 │ 7            │ 164              │ 57.7863±0.337388 │ 0.66088          │ 0            │ 0.0±0.0         │ 16        │ 140.199±58.1006 │
│ 2   │ julia  │ false   │ missing │ 512  │ 137.482±50.6595 │ 1            │ 39               │ 20.0368±0.763614 │ 0.592931         │ 0            │ 0.0±0.0         │ 4         │ 62.4249±33.4451 │
│ 3   │ julia  │ true    │ missing │ 1024 │ 294.164±29.4833 │ 7            │ 164              │ 139.536±0.475507 │ 0.823721         │ 0            │ 0.0±0.0         │ 16        │ 136.297±27.3562 │
│ 4   │ julia  │ false   │ missing │ 1024 │ 162.861±35.7169 │ 1            │ 39               │ 58.8946±0.599732 │ 0.658443         │ 0            │ 0.0±0.0         │ 4         │ 59.4449±27.0149 │
│ 5   │ julia  │ true    │ missing │ 2048 │ 588.478±58.9196 │ 7            │ 164              │ 448.263±0.449248 │ 0.869841         │ 0            │ 0.0±0.0         │ 16        │ 166.56±82.9407  │
│ 6   │ julia  │ false   │ missing │ 2048 │ 299.689±21.5204 │ 1            │ 39               │ 208.366±0.545407 │ 0.678938         │ 0            │ 0.0±0.0         │ 4         │ 50.5025±11.8467 │
```

Register usage goes down, and kernel is quite a bit faster.

**Comment by jrevels** [comment]
Yup, this shouldn't affect the arity-scaling benchmark (since all arguments there are differentiated against), so it's good to see that it doesn't in reality.

Thanks for the measurements, this looks like a strict improvement, so I'll merge. 

At some point, it'd still be great for a more knowledgeable person than me (i.e. @maleadt or @vchuravy) to look at the generated GPU/LLVM code here and make sure that this implementation is squeezing out as much performance as this approach allows, e.g. make sure there aren't any accidental extra compute/memory ops being introduced/masked by the other runtime benefits of the approach.

**Pull request merged**
